### ISSUE TITLE
pause required on line #73 for azure principal

### ISSUE THREAD

**Issue by tacowan** [cf-platform-eng/bosh-azure-template#10]
/cf-platform-eng/bosh-azure-template/blob/master/create_azure_principal_powershell.txt 
I had to add a pause before role assignment due to a "Principal not found" error.  A race condition where the role assignment happens before the directory has fully committed the new service principal.

$AzureServicePrincipal = New-AzureRmADServicePrincipal -ApplicationId $ADApplication.ApplicationId
Start-Sleep -s 10
$RoleAssignment = ...

**Comment by danhigham** [comment]
This issue has been addressed, please see the following commit;

https://github.com/cf-platform-eng/bosh-azure-template/commit/8977c12988836d67d97f748b30d40d65826c90ec
