### ISSUE TITLE
PS failure on New-AzureRmRoleAssignment, likely due to timing

### ISSUE THREAD

**Issue by CraigWiand** [cf-platform-eng/bosh-azure-template#5]
When I ran create_azure_principal_powershell.txt I received the error: 

```
New-AzureRmRoleAssignment : PrincipalNotFound: Principal {SPN.ObjectID Guid }does not exist in the directory {Tenant_ID}.
At \Cloud Foundry\Powershell\ServicePrincipal.ps1:76 char:19
+ ... ssignment = New-AzureRmRoleAssignment -RoleDefinitionName Contributor ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

```

But if I subsequently ran the New-AzureRmRoleAssignment command manually with the CLIENT_ID GUID, it worked fine.  I suspect this is a async/timing issue which could be corrected similar to what is done between the SPN creation and Role assignment steps in the [Azure Cli script ](https://github.com/cf-platform-eng/bosh-azure-template/blob/master/create_azure_principal.sh) (i.e. sleep 4)

Thanks!

**Comment by jeenalshah** [comment]
this is fixed
