### ISSUE TITLE
Why use bootstrap.py in S3 not github?

### ISSUE THREAD

**Issue by bingosummer** [cf-platform-eng/bosh-azure-template#7]
https://github.com/cf-platform-eng/bosh-azure-template/blob/master/azuredeploy.json#L361

**Comment by jeenalshah** [comment]
bootstrap.py is also on github. what is the concern ?

**Comment by danhigham** [comment]
We deploy assets to S3 automatically from our CI pipeline. This allows us to keep versioned releases and we also consider the availability of AWS to be more reliable than Github.
