### ISSUE TITLE
whereismyip.com is no longer available

### ISSUE THREAD

**Issue by CraigWiand** [cf-platform-eng/bosh-azure-template#8]
This uses whereismyip.com  
https://github.com/cf-platform-eng/bosh-azure-template/blob/master/install_steps/setup_dns.py#L19
this domain appears to not be available anymore.  Perhaps the intent was to use https://www.whatismyip.com/ ? 

If we need to get the external endpoint, perhaps we can evaluate using the Azure ARM queries to get the external IP?

**Comment by anweiss** [comment]
+1

**Comment by anweiss** [comment]
After testing a couple of different URLs, I found that http://www.whereisip.net/ seems to do the trick in terms of the way the screen scrape works in the script

**Comment by danhigham** [comment]
This issue has been resolved.
