### ISSUE TITLE
Additional input validation for Client-ID and Tenant-ID

### ISSUE THREAD

**Issue by CraigWiand** [cf-platform-eng/bosh-azure-template#9]
We have seen companies trying to deploy the marketplace template to Azure and really struggle with getting the right Client-Id and Tenant-Id parameters.  To help mitigate this, could we add a validation RegEx to those parameters to ensure that they are formatting them as GUIDs/UUIDs?

Specifically, adding a RegEx under here: https://github.com/cf-platform-eng/bosh-azure-template/blob/master/CreateUiDefinition.json#L45 and here https://github.com/cf-platform-eng/bosh-azure-template/blob/master/CreateUiDefinition.json#L54 with a validation message

**Comment by danhigham** [comment]
This issue has been addressed, however the change is still undergoing approval with Microsoft before it hits the marketplace.
